---
- name: Include globals from etc/agra
  ansible.builtin.include_vars:
    file: "/etc/agra/globals.yml"
    name: agra_globals
  delegate_to: localhost
  run_once: true
- name: Merge globals into top-level namespace
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop: "{{ agra_globals | dict2items }}"
  delegate_to: localhost
  run_once: true
- name: Include passwords from etc/agra (vaulted or plain)
  ansible.builtin.include_vars:
    file: "/etc/agra/passwords.yml"
    name: agra_passwords
  delegate_to: localhost
  run_once: true
  ignore_errors: true
- name: Merge passwords into top-level namespace
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop: "{{ (agra_passwords | default({})) | dict2items }}"
  delegate_to: localhost
  run_once: true
