---
- name: restart node_exporter
  ansible.builtin.debug:
    msg: "Restart handler triggered"
  changed_when: true
  notify:
    - restart node_exporter docker

- name: restart node_exporter docker
  ansible.builtin.shell:
    cmd: RUNTIME=$(command -v podman >/dev/null 2>&1 && echo podman || echo docker); $RUNTIME restart {{ node_exporter_container_name }} || true
  when:
    - enable_node_exporter | default(true) | bool
  changed_when: true
  ignore_errors: true