---
- name: restart grafana
  ansible.builtin.debug:
    msg: "Restart grafana triggered"
  changed_when: true
  notify:
    - restart grafana docker

- name: restart grafana docker
  ansible.builtin.shell:
    cmd: RUNTIME=$(command -v podman >/dev/null 2>&1 && echo podman || echo docker); $RUNTIME restart {{ grafana_container_name }} || true
  when:
    - enable_grafana | default(true) | bool
  changed_when: true
  ignore_errors: true
