---
- name: Keepalived (Native) - Install keepalived package (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - "{{ keepalived_native_package_name }}"
      - curl
      - iproute2
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == 'Debian'
  tags: ['keepalived', 'native', 'install']

- name: Keepalived (Native) - Install keepalived package (RHEL/CentOS)
  ansible.builtin.dnf:
    name:
      - "{{ keepalived_native_package_name }}"
      - curl
      - iproute
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
  tags: ['keepalived', 'native', 'install']

- name: Keepalived (Native) - Enable and start keepalived service
  ansible.builtin.service:
    name: "{{ keepalived_service_name }}"
    state: started
    enabled: true
  register: _ka_start
  ignore_errors: true
  tags: ['keepalived', 'native', 'service']

- name: Keepalived (Native) - Sysctl: allow binding VIP non-local untuk backup node
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/99-agra-keepalived.conf
    reload: true
  ignore_errors: true
  tags: ['keepalived', 'native', 'sysctl']
